name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm install

  unit-testing:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm install
      - name: Run unit testing command
        run: npm test

  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret
        env: 
          MY_SECRET: ${{ secrets.TOP_SECRET}}
        run: echo "My secret is ${MY_SECRET}" | sed 's/./& /g'